// Materials definition for Lathe Craft Workshop

export const MATERIALS = {
  wood: {
    id: 'wood',
    name: '木材 (ヒノキ)',
    shortName: '木材',
    icon: '🪵',
    category: '木質素材',
    hardness: 0.35, // Cut speed multiplier (lower = easier to cut)
    hardnessStars: '★☆☆☆☆',
    hardnessLevel: 1,
    hardnessLabel: '極軟 (切削性: 易)',
    roughnessInit: 0.6,
    colorBase: '#c49a6c',
    colorDark: '#8b5a2b',
    colorLight: '#dfbe99',
    chipColor: '#d2ab7a',
    sparkChance: 0.0,
    pricePerStock: 10,
    features: ['初心者向け', 'サクサク切削', '滑らか木肌'],
    description: '柔らかく加工しやすい初心者向けの工作用木材。'
  },
  aluminum: {
    id: 'aluminum',
    name: 'アルミニウム (A5052)',
    shortName: 'アルミ',
    icon: '⚙️',
    category: '軽金属',
    hardness: 0.6,
    hardnessStars: '★★☆☆☆',
    hardnessLevel: 2,
    hardnessLabel: '軟質 (標準金属)',
    roughnessInit: 0.5,
    colorBase: '#d0d7de',
    colorDark: '#8c959f',
    colorLight: '#f6f8fa',
    chipColor: '#e1e4e8',
    sparkChance: 0.02,
    pricePerStock: 30,
    features: ['切削性良好', '白銀の光沢', '精密加工向'],
    description: '軽量で切削性に優れる標準的な金属素材。'
  },
  brass: {
    id: 'brass',
    name: '真鍮 (黄銅 / C3604)',
    shortName: '真鍮',
    icon: '🟡',
    category: '銅合金',
    hardness: 0.75,
    hardnessStars: '★★★☆☆',
    hardnessLevel: 3,
    hardnessLabel: '中硬 (装飾・精密)',
    roughnessInit: 0.45,
    colorBase: '#d4af37',
    colorDark: '#997a15',
    colorLight: '#f3e5ab',
    chipColor: '#e5c158',
    sparkChance: 0.05,
    pricePerStock: 60,
    features: ['黄金の輝き', '鏡面研磨◎', '工芸・装飾品'],
    description: '美しい黄金色の光沢を持つ。装飾品や精密部品に最適。'
  },
  steel: {
    id: 'steel',
    name: '炭素鋼 (S45C)',
    shortName: '炭素鋼',
    icon: '🔩',
    category: '高張力鋼',
    hardness: 0.95,
    hardnessStars: '★★★★☆',
    hardnessLevel: 4,
    hardnessLabel: '硬質 (高強度鋼)',
    roughnessInit: 0.55,
    colorBase: '#71767a',
    colorDark: '#3b3e40',
    colorLight: '#aeb3b7',
    chipColor: '#8a9094',
    sparkChance: 0.25,
    pricePerStock: 120,
    features: ['適度な火花', '高耐久・硬質', '機械構造用'],
    description: '強度が高い硬質スチール。切削時に適度な火花が飛ぶ。'
  },
  titanium: {
    id: 'titanium',
    name: 'チタン合金 (Ti-6Al-4V)',
    shortName: 'チタン',
    icon: '🚀',
    category: '難削耐熱合金',
    hardness: 1.25,
    hardnessStars: '★★★★★',
    hardnessLevel: 5,
    hardnessLabel: '極硬 (最高難度)',
    roughnessInit: 0.45,
    colorBase: '#5c6470',
    colorDark: '#2f343b',
    colorLight: '#949ba6',
    chipColor: '#7b8390',
    sparkChance: 0.35,
    pricePerStock: 300,
    features: ['航空宇宙規格', '超高強度', '超高額報酬'],
    description: '航空宇宙規格の高強度合金。高額報酬のターゲット。'
  }
};
